services:
  # Backend Web Service
  - type: web
    name: emp-app-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_URL
        sync: false # You will need to set this in the Render Dashboard
      - key: FRONTEND_URL
        fromService:
          name: emp-app-frontend
          type: static_site
          property: url

  # Frontend Static Site
  - type: static_site
    name: emp-app-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: emp-app-backend
          type: web
          property: url
